apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tutorial-pipeline
spec:
  resources:
    - name: tekton1-git
      type: git
    - name: tekton1-image
      type: image
  params:
    - name: BUILDER_IMAGE
      description: Image used to do the build
      default: quay.io/buildah/stable:v1.11.0
    - name: DOCKERFILE
      description: Location of the docker file
      default: ./Dockerfile
    - name: TLSVERIFY
      description: True or False for TLS Verificatoin
      default: "false"
    - name: pathToContext
      description: path to context
      default: /workspace/tekton1-git
    - name: targetNamespace
      description: namespace
      default: tekton-lab
  tasks:
    - name: build-push
      taskRef:
        name: buildah
      params:
        - name: BUILDER_IMAGE
          value: "quay.io/buildah/stable:v1.11.0"
        - name: DOCKERFILE
          value: "/Dockerfile"
        - name: TLSVERIFY
          value: "false"
      resources:
        inputs:
          - name: tekton1-git
            resource: tekton1-git
        outputs:
          - name:  tekton1-image
            resource: tekton1-image
    - name: deploy-to-cluster
      taskRef:
        name: deploy-cm
      params:
        - name: pathToContext
          value: "/workspace/tekton1-git"
        - name: targetNamespace
          value: "tekton-lab"
      resources:
        inputs:
          - name: tekton1-git
            resource: tekton1-git
      runAfter:
        - build-push
